/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedBecomeCreatorRouteImport } from './routes/_authenticated/become-creator'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedStudioSubscriptionsRouteImport } from './routes/_authenticated/studio_.subscriptions'
import { Route as AuthenticatedStudioPayoutsRouteImport } from './routes/_authenticated/studio_.payouts'
import { Route as AuthenticatedStudioArticlesNewRouteImport } from './routes/_authenticated/studio_.articles.new'
import { Route as AuthenticatedUUsernamePostSlugRouteImport } from './routes/_authenticated/u.$username_.post.$slug'
import { Route as AuthenticatedUUsernameArticleSlugRouteImport } from './routes/_authenticated/u.$username_.article.$slug'
import { Route as AuthenticatedStudioArticlesPostIdEditRouteImport } from './routes/_authenticated/studio_.articles.$postId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBecomeCreatorRoute =
  AuthenticatedBecomeCreatorRouteImport.update({
    id: '/become-creator',
    path: '/become-creator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioSubscriptionsRoute =
  AuthenticatedStudioSubscriptionsRouteImport.update({
    id: '/studio_/subscriptions',
    path: '/studio/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioPayoutsRoute =
  AuthenticatedStudioPayoutsRouteImport.update({
    id: '/studio_/payouts',
    path: '/studio/payouts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioArticlesNewRoute =
  AuthenticatedStudioArticlesNewRouteImport.update({
    id: '/studio_/articles/new',
    path: '/studio/articles/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernamePostSlugRoute =
  AuthenticatedUUsernamePostSlugRouteImport.update({
    id: '/u/$username_/post/$slug',
    path: '/u/$username/post/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernameArticleSlugRoute =
  AuthenticatedUUsernameArticleSlugRouteImport.update({
    id: '/u/$username_/article/$slug',
    path: '/u/$username/article/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioArticlesPostIdEditRoute =
  AuthenticatedStudioArticlesPostIdEditRouteImport.update({
    id: '/studio_/articles/$postId/edit',
    path: '/studio/articles/$postId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/studio/payouts': typeof AuthenticatedStudioPayoutsRoute
  '/studio/subscriptions': typeof AuthenticatedStudioSubscriptionsRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/studio/articles/new': typeof AuthenticatedStudioArticlesNewRoute
  '/studio/articles/$postId/edit': typeof AuthenticatedStudioArticlesPostIdEditRoute
  '/u/$username/article/$slug': typeof AuthenticatedUUsernameArticleSlugRoute
  '/u/$username/post/$slug': typeof AuthenticatedUUsernamePostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/studio/payouts': typeof AuthenticatedStudioPayoutsRoute
  '/studio/subscriptions': typeof AuthenticatedStudioSubscriptionsRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/studio/articles/new': typeof AuthenticatedStudioArticlesNewRoute
  '/studio/articles/$postId/edit': typeof AuthenticatedStudioArticlesPostIdEditRoute
  '/u/$username/article/$slug': typeof AuthenticatedUUsernameArticleSlugRoute
  '/u/$username/post/$slug': typeof AuthenticatedUUsernamePostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/studio_/payouts': typeof AuthenticatedStudioPayoutsRoute
  '/_authenticated/studio_/subscriptions': typeof AuthenticatedStudioSubscriptionsRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/studio_/articles/new': typeof AuthenticatedStudioArticlesNewRoute
  '/_authenticated/studio_/articles/$postId/edit': typeof AuthenticatedStudioArticlesPostIdEditRoute
  '/_authenticated/u/$username_/article/$slug': typeof AuthenticatedUUsernameArticleSlugRoute
  '/_authenticated/u/$username_/post/$slug': typeof AuthenticatedUUsernamePostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/become-creator'
    | '/feed'
    | '/settings'
    | '/studio'
    | '/studio/payouts'
    | '/studio/subscriptions'
    | '/u/$username'
    | '/studio/articles/new'
    | '/studio/articles/$postId/edit'
    | '/u/$username/article/$slug'
    | '/u/$username/post/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/become-creator'
    | '/feed'
    | '/settings'
    | '/studio'
    | '/studio/payouts'
    | '/studio/subscriptions'
    | '/u/$username'
    | '/studio/articles/new'
    | '/studio/articles/$postId/edit'
    | '/u/$username/article/$slug'
    | '/u/$username/post/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/become-creator'
    | '/_authenticated/feed'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/studio_/payouts'
    | '/_authenticated/studio_/subscriptions'
    | '/_authenticated/u/$username'
    | '/_authenticated/studio_/articles/new'
    | '/_authenticated/studio_/articles/$postId/edit'
    | '/_authenticated/u/$username_/article/$slug'
    | '/_authenticated/u/$username_/post/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/become-creator': {
      id: '/_authenticated/become-creator'
      path: '/become-creator'
      fullPath: '/become-creator'
      preLoaderRoute: typeof AuthenticatedBecomeCreatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/subscriptions': {
      id: '/_authenticated/studio_/subscriptions'
      path: '/studio/subscriptions'
      fullPath: '/studio/subscriptions'
      preLoaderRoute: typeof AuthenticatedStudioSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/payouts': {
      id: '/_authenticated/studio_/payouts'
      path: '/studio/payouts'
      fullPath: '/studio/payouts'
      preLoaderRoute: typeof AuthenticatedStudioPayoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/articles/new': {
      id: '/_authenticated/studio_/articles/new'
      path: '/studio/articles/new'
      fullPath: '/studio/articles/new'
      preLoaderRoute: typeof AuthenticatedStudioArticlesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/post/$slug': {
      id: '/_authenticated/u/$username_/post/$slug'
      path: '/u/$username/post/$slug'
      fullPath: '/u/$username/post/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernamePostSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/article/$slug': {
      id: '/_authenticated/u/$username_/article/$slug'
      path: '/u/$username/article/$slug'
      fullPath: '/u/$username/article/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernameArticleSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/articles/$postId/edit': {
      id: '/_authenticated/studio_/articles/$postId/edit'
      path: '/studio/articles/$postId/edit'
      fullPath: '/studio/articles/$postId/edit'
      preLoaderRoute: typeof AuthenticatedStudioArticlesPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBecomeCreatorRoute: typeof AuthenticatedBecomeCreatorRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedStudioPayoutsRoute: typeof AuthenticatedStudioPayoutsRoute
  AuthenticatedStudioSubscriptionsRoute: typeof AuthenticatedStudioSubscriptionsRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedStudioArticlesNewRoute: typeof AuthenticatedStudioArticlesNewRoute
  AuthenticatedStudioArticlesPostIdEditRoute: typeof AuthenticatedStudioArticlesPostIdEditRoute
  AuthenticatedUUsernameArticleSlugRoute: typeof AuthenticatedUUsernameArticleSlugRoute
  AuthenticatedUUsernamePostSlugRoute: typeof AuthenticatedUUsernamePostSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBecomeCreatorRoute: AuthenticatedBecomeCreatorRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedStudioPayoutsRoute: AuthenticatedStudioPayoutsRoute,
  AuthenticatedStudioSubscriptionsRoute: AuthenticatedStudioSubscriptionsRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedStudioArticlesNewRoute: AuthenticatedStudioArticlesNewRoute,
  AuthenticatedStudioArticlesPostIdEditRoute:
    AuthenticatedStudioArticlesPostIdEditRoute,
  AuthenticatedUUsernameArticleSlugRoute:
    AuthenticatedUUsernameArticleSlugRoute,
  AuthenticatedUUsernamePostSlugRoute: AuthenticatedUUsernamePostSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
