/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedStudioRouteImport } from './routes/_authenticated/studio'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedFeedRouteImport } from './routes/_authenticated/feed'
import { Route as AuthenticatedBecomeCreatorRouteImport } from './routes/_authenticated/become-creator'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedStudioSubscriptionsRouteImport } from './routes/_authenticated/studio_.subscriptions'
import { Route as AuthenticatedStudioPhotographyRouteImport } from './routes/_authenticated/studio_.photography'
import { Route as AuthenticatedStudioPayoutsRouteImport } from './routes/_authenticated/studio_.payouts'
import { Route as AuthenticatedStudioCoursesRouteImport } from './routes/_authenticated/studio_.courses'
import { Route as AuthenticatedStudioAudioRouteImport } from './routes/_authenticated/studio_.audio'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings_.security'
import { Route as AuthenticatedSettingsProfileTabsRouteImport } from './routes/_authenticated/settings_.profile-tabs'
import { Route as AuthenticatedSettingsProfileRouteImport } from './routes/_authenticated/settings_.profile'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings_.notifications'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings_.account'
import { Route as AuthenticatedStudioCoursesNewRouteImport } from './routes/_authenticated/studio_.courses.new'
import { Route as AuthenticatedStudioArticlesNewRouteImport } from './routes/_authenticated/studio_.articles.new'
import { Route as AuthenticatedUUsernamePostSlugRouteImport } from './routes/_authenticated/u.$username_.post.$slug'
import { Route as AuthenticatedUUsernamePodcastSlugRouteImport } from './routes/_authenticated/u.$username_.podcast.$slug'
import { Route as AuthenticatedUUsernamePhotographySlugRouteImport } from './routes/_authenticated/u.$username_.photography.$slug'
import { Route as AuthenticatedUUsernameCourseSlugRouteImport } from './routes/_authenticated/u.$username_.course.$slug'
import { Route as AuthenticatedUUsernameAudioSlugRouteImport } from './routes/_authenticated/u.$username_.audio.$slug'
import { Route as AuthenticatedUUsernameArticleSlugRouteImport } from './routes/_authenticated/u.$username_.article.$slug'
import { Route as AuthenticatedUUsernameAlbumSlugRouteImport } from './routes/_authenticated/u.$username_.album.$slug'
import { Route as AuthenticatedStudioCoursesCourseIdEditRouteImport } from './routes/_authenticated/studio_.courses.$courseId.edit'
import { Route as AuthenticatedStudioArticlesPostIdEditRouteImport } from './routes/_authenticated/studio_.articles.$postId.edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudioRoute = AuthenticatedStudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeedRoute = AuthenticatedFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBecomeCreatorRoute =
  AuthenticatedBecomeCreatorRouteImport.update({
    id: '/become-creator',
    path: '/become-creator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudioSubscriptionsRoute =
  AuthenticatedStudioSubscriptionsRouteImport.update({
    id: '/studio_/subscriptions',
    path: '/studio/subscriptions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioPhotographyRoute =
  AuthenticatedStudioPhotographyRouteImport.update({
    id: '/studio_/photography',
    path: '/studio/photography',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioPayoutsRoute =
  AuthenticatedStudioPayoutsRouteImport.update({
    id: '/studio_/payouts',
    path: '/studio/payouts',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioCoursesRoute =
  AuthenticatedStudioCoursesRouteImport.update({
    id: '/studio_/courses',
    path: '/studio/courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioAudioRoute =
  AuthenticatedStudioAudioRouteImport.update({
    id: '/studio_/audio',
    path: '/studio/audio',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings_/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileTabsRoute =
  AuthenticatedSettingsProfileTabsRouteImport.update({
    id: '/settings_/profile-tabs',
    path: '/settings/profile-tabs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsProfileRoute =
  AuthenticatedSettingsProfileRouteImport.update({
    id: '/settings_/profile',
    path: '/settings/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/settings_/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/settings_/account',
    path: '/settings/account',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioCoursesNewRoute =
  AuthenticatedStudioCoursesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedStudioCoursesRoute,
  } as any)
const AuthenticatedStudioArticlesNewRoute =
  AuthenticatedStudioArticlesNewRouteImport.update({
    id: '/studio_/articles/new',
    path: '/studio/articles/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernamePostSlugRoute =
  AuthenticatedUUsernamePostSlugRouteImport.update({
    id: '/u/$username_/post/$slug',
    path: '/u/$username/post/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernamePodcastSlugRoute =
  AuthenticatedUUsernamePodcastSlugRouteImport.update({
    id: '/u/$username_/podcast/$slug',
    path: '/u/$username/podcast/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernamePhotographySlugRoute =
  AuthenticatedUUsernamePhotographySlugRouteImport.update({
    id: '/u/$username_/photography/$slug',
    path: '/u/$username/photography/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernameCourseSlugRoute =
  AuthenticatedUUsernameCourseSlugRouteImport.update({
    id: '/u/$username_/course/$slug',
    path: '/u/$username/course/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernameAudioSlugRoute =
  AuthenticatedUUsernameAudioSlugRouteImport.update({
    id: '/u/$username_/audio/$slug',
    path: '/u/$username/audio/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernameArticleSlugRoute =
  AuthenticatedUUsernameArticleSlugRouteImport.update({
    id: '/u/$username_/article/$slug',
    path: '/u/$username/article/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUUsernameAlbumSlugRoute =
  AuthenticatedUUsernameAlbumSlugRouteImport.update({
    id: '/u/$username_/album/$slug',
    path: '/u/$username/album/$slug',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedStudioCoursesCourseIdEditRoute =
  AuthenticatedStudioCoursesCourseIdEditRouteImport.update({
    id: '/$courseId/edit',
    path: '/$courseId/edit',
    getParentRoute: () => AuthenticatedStudioCoursesRoute,
  } as any)
const AuthenticatedStudioArticlesPostIdEditRoute =
  AuthenticatedStudioArticlesPostIdEditRouteImport.update({
    id: '/studio_/articles/$postId/edit',
    path: '/studio/articles/$postId/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/profile-tabs': typeof AuthenticatedSettingsProfileTabsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/studio/audio': typeof AuthenticatedStudioAudioRoute
  '/studio/courses': typeof AuthenticatedStudioCoursesRouteWithChildren
  '/studio/payouts': typeof AuthenticatedStudioPayoutsRoute
  '/studio/photography': typeof AuthenticatedStudioPhotographyRoute
  '/studio/subscriptions': typeof AuthenticatedStudioSubscriptionsRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/studio/articles/new': typeof AuthenticatedStudioArticlesNewRoute
  '/studio/courses/new': typeof AuthenticatedStudioCoursesNewRoute
  '/studio/articles/$postId/edit': typeof AuthenticatedStudioArticlesPostIdEditRoute
  '/studio/courses/$courseId/edit': typeof AuthenticatedStudioCoursesCourseIdEditRoute
  '/u/$username/album/$slug': typeof AuthenticatedUUsernameAlbumSlugRoute
  '/u/$username/article/$slug': typeof AuthenticatedUUsernameArticleSlugRoute
  '/u/$username/audio/$slug': typeof AuthenticatedUUsernameAudioSlugRoute
  '/u/$username/course/$slug': typeof AuthenticatedUUsernameCourseSlugRoute
  '/u/$username/photography/$slug': typeof AuthenticatedUUsernamePhotographySlugRoute
  '/u/$username/podcast/$slug': typeof AuthenticatedUUsernamePodcastSlugRoute
  '/u/$username/post/$slug': typeof AuthenticatedUUsernamePostSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/feed': typeof AuthenticatedFeedRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/studio': typeof AuthenticatedStudioRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/profile': typeof AuthenticatedSettingsProfileRoute
  '/settings/profile-tabs': typeof AuthenticatedSettingsProfileTabsRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/studio/audio': typeof AuthenticatedStudioAudioRoute
  '/studio/courses': typeof AuthenticatedStudioCoursesRouteWithChildren
  '/studio/payouts': typeof AuthenticatedStudioPayoutsRoute
  '/studio/photography': typeof AuthenticatedStudioPhotographyRoute
  '/studio/subscriptions': typeof AuthenticatedStudioSubscriptionsRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
  '/studio/articles/new': typeof AuthenticatedStudioArticlesNewRoute
  '/studio/courses/new': typeof AuthenticatedStudioCoursesNewRoute
  '/studio/articles/$postId/edit': typeof AuthenticatedStudioArticlesPostIdEditRoute
  '/studio/courses/$courseId/edit': typeof AuthenticatedStudioCoursesCourseIdEditRoute
  '/u/$username/album/$slug': typeof AuthenticatedUUsernameAlbumSlugRoute
  '/u/$username/article/$slug': typeof AuthenticatedUUsernameArticleSlugRoute
  '/u/$username/audio/$slug': typeof AuthenticatedUUsernameAudioSlugRoute
  '/u/$username/course/$slug': typeof AuthenticatedUUsernameCourseSlugRoute
  '/u/$username/photography/$slug': typeof AuthenticatedUUsernamePhotographySlugRoute
  '/u/$username/podcast/$slug': typeof AuthenticatedUUsernamePodcastSlugRoute
  '/u/$username/post/$slug': typeof AuthenticatedUUsernamePostSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/become-creator': typeof AuthenticatedBecomeCreatorRoute
  '/_authenticated/feed': typeof AuthenticatedFeedRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/studio': typeof AuthenticatedStudioRoute
  '/_authenticated/settings_/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings_/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings_/profile': typeof AuthenticatedSettingsProfileRoute
  '/_authenticated/settings_/profile-tabs': typeof AuthenticatedSettingsProfileTabsRoute
  '/_authenticated/settings_/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/studio_/audio': typeof AuthenticatedStudioAudioRoute
  '/_authenticated/studio_/courses': typeof AuthenticatedStudioCoursesRouteWithChildren
  '/_authenticated/studio_/payouts': typeof AuthenticatedStudioPayoutsRoute
  '/_authenticated/studio_/photography': typeof AuthenticatedStudioPhotographyRoute
  '/_authenticated/studio_/subscriptions': typeof AuthenticatedStudioSubscriptionsRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
  '/_authenticated/studio_/articles/new': typeof AuthenticatedStudioArticlesNewRoute
  '/_authenticated/studio_/courses/new': typeof AuthenticatedStudioCoursesNewRoute
  '/_authenticated/studio_/articles/$postId/edit': typeof AuthenticatedStudioArticlesPostIdEditRoute
  '/_authenticated/studio_/courses/$courseId/edit': typeof AuthenticatedStudioCoursesCourseIdEditRoute
  '/_authenticated/u/$username_/album/$slug': typeof AuthenticatedUUsernameAlbumSlugRoute
  '/_authenticated/u/$username_/article/$slug': typeof AuthenticatedUUsernameArticleSlugRoute
  '/_authenticated/u/$username_/audio/$slug': typeof AuthenticatedUUsernameAudioSlugRoute
  '/_authenticated/u/$username_/course/$slug': typeof AuthenticatedUUsernameCourseSlugRoute
  '/_authenticated/u/$username_/photography/$slug': typeof AuthenticatedUUsernamePhotographySlugRoute
  '/_authenticated/u/$username_/podcast/$slug': typeof AuthenticatedUUsernamePodcastSlugRoute
  '/_authenticated/u/$username_/post/$slug': typeof AuthenticatedUUsernamePostSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/become-creator'
    | '/feed'
    | '/notifications'
    | '/settings'
    | '/studio'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/profile-tabs'
    | '/settings/security'
    | '/studio/audio'
    | '/studio/courses'
    | '/studio/payouts'
    | '/studio/photography'
    | '/studio/subscriptions'
    | '/u/$username'
    | '/studio/articles/new'
    | '/studio/courses/new'
    | '/studio/articles/$postId/edit'
    | '/studio/courses/$courseId/edit'
    | '/u/$username/album/$slug'
    | '/u/$username/article/$slug'
    | '/u/$username/audio/$slug'
    | '/u/$username/course/$slug'
    | '/u/$username/photography/$slug'
    | '/u/$username/podcast/$slug'
    | '/u/$username/post/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/become-creator'
    | '/feed'
    | '/notifications'
    | '/settings'
    | '/studio'
    | '/settings/account'
    | '/settings/notifications'
    | '/settings/profile'
    | '/settings/profile-tabs'
    | '/settings/security'
    | '/studio/audio'
    | '/studio/courses'
    | '/studio/payouts'
    | '/studio/photography'
    | '/studio/subscriptions'
    | '/u/$username'
    | '/studio/articles/new'
    | '/studio/courses/new'
    | '/studio/articles/$postId/edit'
    | '/studio/courses/$courseId/edit'
    | '/u/$username/album/$slug'
    | '/u/$username/article/$slug'
    | '/u/$username/audio/$slug'
    | '/u/$username/course/$slug'
    | '/u/$username/photography/$slug'
    | '/u/$username/podcast/$slug'
    | '/u/$username/post/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/become-creator'
    | '/_authenticated/feed'
    | '/_authenticated/notifications'
    | '/_authenticated/settings'
    | '/_authenticated/studio'
    | '/_authenticated/settings_/account'
    | '/_authenticated/settings_/notifications'
    | '/_authenticated/settings_/profile'
    | '/_authenticated/settings_/profile-tabs'
    | '/_authenticated/settings_/security'
    | '/_authenticated/studio_/audio'
    | '/_authenticated/studio_/courses'
    | '/_authenticated/studio_/payouts'
    | '/_authenticated/studio_/photography'
    | '/_authenticated/studio_/subscriptions'
    | '/_authenticated/u/$username'
    | '/_authenticated/studio_/articles/new'
    | '/_authenticated/studio_/courses/new'
    | '/_authenticated/studio_/articles/$postId/edit'
    | '/_authenticated/studio_/courses/$courseId/edit'
    | '/_authenticated/u/$username_/album/$slug'
    | '/_authenticated/u/$username_/article/$slug'
    | '/_authenticated/u/$username_/audio/$slug'
    | '/_authenticated/u/$username_/course/$slug'
    | '/_authenticated/u/$username_/photography/$slug'
    | '/_authenticated/u/$username_/podcast/$slug'
    | '/_authenticated/u/$username_/post/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/studio': {
      id: '/_authenticated/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof AuthenticatedStudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feed': {
      id: '/_authenticated/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof AuthenticatedFeedRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/become-creator': {
      id: '/_authenticated/become-creator'
      path: '/become-creator'
      fullPath: '/become-creator'
      preLoaderRoute: typeof AuthenticatedBecomeCreatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/subscriptions': {
      id: '/_authenticated/studio_/subscriptions'
      path: '/studio/subscriptions'
      fullPath: '/studio/subscriptions'
      preLoaderRoute: typeof AuthenticatedStudioSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/photography': {
      id: '/_authenticated/studio_/photography'
      path: '/studio/photography'
      fullPath: '/studio/photography'
      preLoaderRoute: typeof AuthenticatedStudioPhotographyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/payouts': {
      id: '/_authenticated/studio_/payouts'
      path: '/studio/payouts'
      fullPath: '/studio/payouts'
      preLoaderRoute: typeof AuthenticatedStudioPayoutsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/courses': {
      id: '/_authenticated/studio_/courses'
      path: '/studio/courses'
      fullPath: '/studio/courses'
      preLoaderRoute: typeof AuthenticatedStudioCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/audio': {
      id: '/_authenticated/studio_/audio'
      path: '/studio/audio'
      fullPath: '/studio/audio'
      preLoaderRoute: typeof AuthenticatedStudioAudioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/security': {
      id: '/_authenticated/settings_/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/profile-tabs': {
      id: '/_authenticated/settings_/profile-tabs'
      path: '/settings/profile-tabs'
      fullPath: '/settings/profile-tabs'
      preLoaderRoute: typeof AuthenticatedSettingsProfileTabsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/profile': {
      id: '/_authenticated/settings_/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthenticatedSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/notifications': {
      id: '/_authenticated/settings_/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings_/account': {
      id: '/_authenticated/settings_/account'
      path: '/settings/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/courses/new': {
      id: '/_authenticated/studio_/courses/new'
      path: '/new'
      fullPath: '/studio/courses/new'
      preLoaderRoute: typeof AuthenticatedStudioCoursesNewRouteImport
      parentRoute: typeof AuthenticatedStudioCoursesRoute
    }
    '/_authenticated/studio_/articles/new': {
      id: '/_authenticated/studio_/articles/new'
      path: '/studio/articles/new'
      fullPath: '/studio/articles/new'
      preLoaderRoute: typeof AuthenticatedStudioArticlesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/post/$slug': {
      id: '/_authenticated/u/$username_/post/$slug'
      path: '/u/$username/post/$slug'
      fullPath: '/u/$username/post/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernamePostSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/podcast/$slug': {
      id: '/_authenticated/u/$username_/podcast/$slug'
      path: '/u/$username/podcast/$slug'
      fullPath: '/u/$username/podcast/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernamePodcastSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/photography/$slug': {
      id: '/_authenticated/u/$username_/photography/$slug'
      path: '/u/$username/photography/$slug'
      fullPath: '/u/$username/photography/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernamePhotographySlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/course/$slug': {
      id: '/_authenticated/u/$username_/course/$slug'
      path: '/u/$username/course/$slug'
      fullPath: '/u/$username/course/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernameCourseSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/audio/$slug': {
      id: '/_authenticated/u/$username_/audio/$slug'
      path: '/u/$username/audio/$slug'
      fullPath: '/u/$username/audio/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernameAudioSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/article/$slug': {
      id: '/_authenticated/u/$username_/article/$slug'
      path: '/u/$username/article/$slug'
      fullPath: '/u/$username/article/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernameArticleSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username_/album/$slug': {
      id: '/_authenticated/u/$username_/album/$slug'
      path: '/u/$username/album/$slug'
      fullPath: '/u/$username/album/$slug'
      preLoaderRoute: typeof AuthenticatedUUsernameAlbumSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/studio_/courses/$courseId/edit': {
      id: '/_authenticated/studio_/courses/$courseId/edit'
      path: '/$courseId/edit'
      fullPath: '/studio/courses/$courseId/edit'
      preLoaderRoute: typeof AuthenticatedStudioCoursesCourseIdEditRouteImport
      parentRoute: typeof AuthenticatedStudioCoursesRoute
    }
    '/_authenticated/studio_/articles/$postId/edit': {
      id: '/_authenticated/studio_/articles/$postId/edit'
      path: '/studio/articles/$postId/edit'
      fullPath: '/studio/articles/$postId/edit'
      preLoaderRoute: typeof AuthenticatedStudioArticlesPostIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedStudioCoursesRouteChildren {
  AuthenticatedStudioCoursesNewRoute: typeof AuthenticatedStudioCoursesNewRoute
  AuthenticatedStudioCoursesCourseIdEditRoute: typeof AuthenticatedStudioCoursesCourseIdEditRoute
}

const AuthenticatedStudioCoursesRouteChildren: AuthenticatedStudioCoursesRouteChildren =
  {
    AuthenticatedStudioCoursesNewRoute: AuthenticatedStudioCoursesNewRoute,
    AuthenticatedStudioCoursesCourseIdEditRoute:
      AuthenticatedStudioCoursesCourseIdEditRoute,
  }

const AuthenticatedStudioCoursesRouteWithChildren =
  AuthenticatedStudioCoursesRoute._addFileChildren(
    AuthenticatedStudioCoursesRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBecomeCreatorRoute: typeof AuthenticatedBecomeCreatorRoute
  AuthenticatedFeedRoute: typeof AuthenticatedFeedRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedStudioRoute: typeof AuthenticatedStudioRoute
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsProfileRoute: typeof AuthenticatedSettingsProfileRoute
  AuthenticatedSettingsProfileTabsRoute: typeof AuthenticatedSettingsProfileTabsRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedStudioAudioRoute: typeof AuthenticatedStudioAudioRoute
  AuthenticatedStudioCoursesRoute: typeof AuthenticatedStudioCoursesRouteWithChildren
  AuthenticatedStudioPayoutsRoute: typeof AuthenticatedStudioPayoutsRoute
  AuthenticatedStudioPhotographyRoute: typeof AuthenticatedStudioPhotographyRoute
  AuthenticatedStudioSubscriptionsRoute: typeof AuthenticatedStudioSubscriptionsRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
  AuthenticatedStudioArticlesNewRoute: typeof AuthenticatedStudioArticlesNewRoute
  AuthenticatedStudioArticlesPostIdEditRoute: typeof AuthenticatedStudioArticlesPostIdEditRoute
  AuthenticatedUUsernameAlbumSlugRoute: typeof AuthenticatedUUsernameAlbumSlugRoute
  AuthenticatedUUsernameArticleSlugRoute: typeof AuthenticatedUUsernameArticleSlugRoute
  AuthenticatedUUsernameAudioSlugRoute: typeof AuthenticatedUUsernameAudioSlugRoute
  AuthenticatedUUsernameCourseSlugRoute: typeof AuthenticatedUUsernameCourseSlugRoute
  AuthenticatedUUsernamePhotographySlugRoute: typeof AuthenticatedUUsernamePhotographySlugRoute
  AuthenticatedUUsernamePodcastSlugRoute: typeof AuthenticatedUUsernamePodcastSlugRoute
  AuthenticatedUUsernamePostSlugRoute: typeof AuthenticatedUUsernamePostSlugRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBecomeCreatorRoute: AuthenticatedBecomeCreatorRoute,
  AuthenticatedFeedRoute: AuthenticatedFeedRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedStudioRoute: AuthenticatedStudioRoute,
  AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
  AuthenticatedSettingsNotificationsRoute:
    AuthenticatedSettingsNotificationsRoute,
  AuthenticatedSettingsProfileRoute: AuthenticatedSettingsProfileRoute,
  AuthenticatedSettingsProfileTabsRoute: AuthenticatedSettingsProfileTabsRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
  AuthenticatedStudioAudioRoute: AuthenticatedStudioAudioRoute,
  AuthenticatedStudioCoursesRoute: AuthenticatedStudioCoursesRouteWithChildren,
  AuthenticatedStudioPayoutsRoute: AuthenticatedStudioPayoutsRoute,
  AuthenticatedStudioPhotographyRoute: AuthenticatedStudioPhotographyRoute,
  AuthenticatedStudioSubscriptionsRoute: AuthenticatedStudioSubscriptionsRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
  AuthenticatedStudioArticlesNewRoute: AuthenticatedStudioArticlesNewRoute,
  AuthenticatedStudioArticlesPostIdEditRoute:
    AuthenticatedStudioArticlesPostIdEditRoute,
  AuthenticatedUUsernameAlbumSlugRoute: AuthenticatedUUsernameAlbumSlugRoute,
  AuthenticatedUUsernameArticleSlugRoute:
    AuthenticatedUUsernameArticleSlugRoute,
  AuthenticatedUUsernameAudioSlugRoute: AuthenticatedUUsernameAudioSlugRoute,
  AuthenticatedUUsernameCourseSlugRoute: AuthenticatedUUsernameCourseSlugRoute,
  AuthenticatedUUsernamePhotographySlugRoute:
    AuthenticatedUUsernamePhotographySlugRoute,
  AuthenticatedUUsernamePodcastSlugRoute:
    AuthenticatedUUsernamePodcastSlugRoute,
  AuthenticatedUUsernamePostSlugRoute: AuthenticatedUUsernamePostSlugRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
